### ISSUE TITLE
Allow semver checking against a monorepo package or git submodule

### ISSUE THREAD

**Issue by thclark** [octue/conventional-commits#23]
### Use Case

Sometimes in a repository, you have a folder structure that's like:
```
packages / packagename / package.json
```
We want to be able to override the default location of package.json in such a case.

### Current state

Currently getting errors because the top level drectory doesn't have a package.json.

### Suggested solution

Allow us to specify the location of package.json in the check-semantic-version cli:
```

jobs:
  check-semantic-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Set fetch-depth to 0 to fetch all tags (necessary for git-mkver to determine the correct semantic version).
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - name: Install git-mkver
        run: |
          curl -L https://github.com/idc101/git-mkver/releases/download/v1.2.1/git-mkver-linux-amd64-1.2.1.tar.gz \
          | tar xvz \
          && sudo mv git-mkver /usr/local/bin
      - name: Install semantic version checker
        run: pip install git+https://github.com/octue/conventional-commits
      - name: Check version
        run: check-semantic-version npm --file packages/mypackage/package.json
```
